### ISSUE TITLE
AttributeError: module 'pdpipe' has no attribute 'TokenizeWords'

### ISSUE THREAD

**Issue by shinokada** [pdpipe/pdpipe#16] opened 2019-12-31 09:12 UTC
I tried this from the [API](https://pdpipe.github.io/pdpipe/doc/pdpipe/core.html#pdpipe.core.PdPipelineStage.TokenizeWords) TokenizeWords example.

## Expected Result

Run without error
Output should be

```
   freq               content
1   3.2  [Kick, the, baby, !]
```

## Actual Result

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-a05640023a7e> in <module>
      2 df = pd.DataFrame(
      3      [[3.2, "Kick the baby!"]], [1], ['freq', 'content'])
----> 4 tokenize_stage = pdp.TokenizeWords('content')
      5 tokenize_stage(df)

AttributeError: module 'pdpipe' has no attribute 'TokenizeWords'

```

## Reproduction Steps

```python
import pandas as pd; import pdpipe as pdp;
df = pd.DataFrame(
     [[3.2, "Kick the baby!"]], [1], ['freq', 'content'])
tokenize_stage = pdp.TokenizeWords('content')
tokenize_stage(df)

```

## System Information

```
macOS Catalina
V 10.15.2
```

Please provide some basic information about your system (Python version,
operating system, &c).

Python 3.7.6

**Comment by shaypal5** [comment] 2019-12-31 12:44
Hey @shinokada ,

The TokenizeWords  pipeline stage is an nltk-dependent stage, and as such requires nltk installed.
If `pdpipe` does not find one of its optional dependencies (for now, only `sklearn` and `nltk`), it issues a warning and does not import dependent stages.

Try installing `nltk` in the same Python environment as the one you're using `pdpipe` in and see if the issue is resovled. If it does not, or I'm wrong and you already have `nltk` installed, then please reopen this issue. Until then, I'm closing it.

I will also add documentation in the nltk stages module and in each nltk pipeline stage that informs users about this more clearly.

Thank you for reaching out,
Shay

**Closed by shaypal5** 2019-12-31 12:44 UTC
Labels: invalid

**Comment by shinokada** [comment] 2019-12-31 21:39
Thanks. The following worked.

```
pip3  install --user -U nltk
```

I thought I had installed nltk, but it was in Anaconda.

**Comment by shaypal5** [comment] 2020-01-01 07:46
Hah, happens to all of us, with all those sneaky Python environments! :)
